; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;  The MIT+1 licensing terms apply to all the previous, current and future
;  versions, unless the author provides a public legal charter allowing a
;  designated entity to be exempted from this extra clause. Comply or delete.
;
;      Note: coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;  In this specific case, MIT+1 is not a derivative of the MIT license but
;  due to the peculiar and extreme nature of this source code, the license
;  acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; =============================================================================
;
; RATIONALE
;
; Some embedded systems cannot rely on busybox seamless uncompression feature
; and not going to receive a firmware upgrade. In this condition they can use
; upzexec only with gzip compressed carryload, which is going to cover almost
; all the cases. However, gzip/zcat cannot cover all the scenarios. Hence the
; uzcat as a standalone static assembler micro-utility can provide the format
; flexibility otherwise unleveraged.  This uzcat is a specific implementation
; for uzpexec, and its name is not conflicting with an already installed zcat
;
; =============================================================================
;
; Building:
;   nasm -O2 -f bin uzcat.asm -o uzcat && chmod +x uzcat
;
; Testing:
;   for cmd in gzip xz bzip2 lz4 zstd lzop; do echo $cmd:
;       $cmd -c uzcat.asm | ./uzcat | file -; done
;   gzip -c uzcat.asm | ./uzcat -f  | file -
;   echo info:; ./uzcat <&-
;   nasm -O2 -f bin -d_DO_EXTRA uzcat.asm -o uzcat
;   echo provider:; ./uzcat <&-
;
; =============================================================================

BITS 32
BASE_ADDR equ 0x08048000         ; Loading base definition
org BASE_ADDR

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0     ; e_ident (Magic, 32bit, Data LSB, Version)
  times 8 db 0                   ; Padding for e_ident
  dw 2                           ; e_type (Executable)
  dw 3                           ; e_machine (Intel 80386)
  dd 1                           ; e_version
  dd main_start                  ; e_entry (The starting point of our code)
  dd phdr - elf_header           ; e_phoff (Offset of the Program Header Table)
  dd 0                           ; e_shoff (No Section Header Table, save bytes)
  dd 0                           ; e_flags
  dw 52                          ; e_ehsize (Size of this header)
  dw 32                          ; e_phentsize (Size of a Program Header entry)
  dw 1                           ; e_phnum (Only one segment needed)
  ; ----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  ;
  dw 0, 0, 0                     ; Section info (zeroed out, reclamable)
  ;
  ; ----------------------------------------------------------------------------

phdr:
  dd 1                           ; p_type (PT_LOAD - Segment to load)
  dd 0                           ; p_offset
  dd BASE_ADDR                   ; p_vaddr (Virtual address in memory)
  dd BASE_ADDR                   ; p_paddr
  dd file_end - elf_header       ; p_filesz (Size of the code within the file)
  dd  bss_end - elf_header       ; p_memsz (Size of the code within memory)

  ; ----------------------------------------------------------------------------
  dd 7                           ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                      ; p_align (Standard page alignment)

  ; Security-by-Design VS Security-by-Subtraction

  ; Because uzcat contains no input parsing logic that could be corrupted and
  ; its fixed size read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; CODE
; ==============================================================================
main_start:
  ; Parse argv to check for -f flag
  pop eax                        ; argc
  pop ebx                        ; argv[0] = program name
  push 1                         ; use STDOUT
  pop edi

.read_magic:
  ; Read first 4 bytes from stdin for magic detection
  ; MUST happen BEFORE fork so child inherits correct file position
  push 3                         ; SYS_read
  pop eax
  xor ebx, ebx                   ; stdin = 0
  mov ecx, buf
  mov edx, 4
  int 0x80

  cmp eax, 4
  jne short .do_exit             ; not 4 bytes, exit //TODO: not a short jump

; ------------------------------------------------------------------------------
; Determine decompressor from magic
; Input : EAX = magic number (first 4 bytes of file, little-endian)
; Output: EAX = pointer to decompressor command string (cat, if no match)
; ------------------------------------------------------------------------------
  mov eax, [buf]

.find_cmd:
  mov ecx, vect_size
  mov edx, magics
  mov esi, paths

.loop_cmd:
  cmp ax, [edx]                  ; it compares the first 2 bytes
  je .str_create
  add edx, 2                     ; move forward on magics
  add esi, 5                     ; move forward on commands
  loop .loop_cmd
  cmp ax, [edx]                  ; gzip compare for zcat as default cmdstr
  je short .do_fork

.use_cat:
  ; Check if argv[1] is "-f"
  xor eax, eax                   ; EAX = 0
  pop ecx                        ; argv[1]
  cmp word [ecx], 0x662d         ; compare with "-f"
  je short parent.do_cat
  jmp .do_exit

.str_create:
  lea edi, [gzpstr]              ; EDI points after "/bin/"
; mov dword ebx, [edi + 1]       ; EBX saves "cat\0"

.copy_loop:
  lodsb                          ; AL = [ESI], ESI++
  stosb                          ; [EDI] = AL, EDI++
  test al, al
  jnz short .copy_loop           ; continue until '\0'

  dec edi
  mov dword [edi], 0x00746163    ; append 'cat\0'
; ------------------------------------------------------------------------------

.do_fork:
  ; Create pipe: pipefd[2] on stack
  sub esp, 8
  mov ebx, esp                   ; ebx = pipefd array
  push 42                        ; SYS_pipe
  pop eax
  int 0x80
  test eax, eax
  jns short .continue

.do_exit:
  jmp short do_exit

.continue:
  pop ebx                        ; pipefd[0] <-- stack
  pop edi                        ; pipefd[1] <-- stack
  push ebx                       ; pipefd[0] --> stack

  ; Fork
  push 2                         ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz short child                 ; FORCE near jump, child has EAX=0

; ==============================================================================
; PARENT PROCESS
; ==============================================================================
parent:
  ; Close read end of pipe
%ifdef _DO_CLOSE
  push 6                         ; SYS_close
  pop eax
  mov ebx, [esp]                 ; pipefd[0]
  int 0x80
%endif

; ------------------------------------------------------------------------------
; DO COPY BY READ / WRITE LOOP
;
; test: cat *.iso | ./uzcat -f  | dd bs=1M of=/dev/null
; slow: 93 MB (88 MiB) copied, 0.0919112 s, 1.0 GB/s (min)
; fast: 93 MB (88 MiB) copied, 0.0638537 s, 1.5 GB/s (max)
; ------------------------------------------------------------------------------
.do_cat:
  ; Write first 4 bytes, already read in buf, to pipe
  push 4                         ; bytes already read, to write
  pop eax
  mov ecx, buf                   ; set once and keep untouched

.pump_loop:
  ; Write to pipe
  mov ebx, edi                   ; pipefd[1]
  mov edx, eax                   ; bytes already read, to write

  push 4                         ; SYS_write
  pop eax
  int 0x80

  ; Read from stdin
  xor ebx, ebx                   ; stdin
  mov dh, 14                     ; buffer size
  mov dl, 0                      ; = 7 * 512

  push 3                         ; SYS_read
  pop eax
  int 0x80

  test eax, eax
  jz short .done                 ; check for EOF
%ifdef _DO_EINTR
  cmp eax, -4                    ; check for -EINTR (if any, ever)
  je short .pump_loop            ; continue
%endif
  js short do_exit
  jmp short .pump_loop           ; continue

.done:
  pop eax
  test eax, eax
  jz short do_exit               ; after do_cat, do_exit

  ; Close the writing pipe to send EOF to the child
  mov al, 6                      ; SYS_close
  mov ebx, edi                   ; pipefd[1]
  int 0x80

  ; Wait for child
  mov al, 7                      ; SYS_waitpid
  dec ebx
  dec ebx                        ; -1 = any child
  xor ecx, ecx                   ; status = NULL
  xor edx, edx                   ; options = 0
  int 0x80

  ; Exit with child's status
  mov bh, ah
  shr ebx, 8                     ; extract exit status
  push 1                         ; SYS_exit
  pop eax
  int 0x80

; ==============================================================================
; CHILD PROCESS
; ==============================================================================
child:
  ; Close write end of pipe
  mov al, 6                      ; SYS_close
  mov ebx, edi                   ; pipefd[1]
  int 0x80

  ; Yann Collet's lz4/lzopcat support only regular file
  pop ebx                        ; pipefd[0] <-- stack
; push 0
  test ecx, ecx
  jz short .use_gzip
  shr ecx, 1
  xor ecx, 2
  jz short .use_stdin
.use_gzip:
  push file_desc
  push cmd_flag
  mov cl, 9

  ; Dup2 read end to stdin
.use_stdin:
  mov al, 63                     ; SYS_dup2
  int 0x80

  ; Close original read end
%ifdef _DO_CLOSE
  push 6                         ; SYS_close
  pop eax
; mov ebx, [esp]                 ; pipefd[0], already set
  int 0x80
%endif

  ; Execve the decompressor
  mov ebx, cmdstr                ; selected decompressor
  push ebx
  mov ecx, esp                   ; argv = [NULL]
  xor edx, edx                   ; envp = NULL (inherit from parent)
  mov al, 11                     ; SYS_execve
  int 0x80

  ; If execve fails, fall through to error

; ==============================================================================
; ERROR HANDLING
; ==============================================================================
do_exit:
  test eax, eax
  jz short .no_error
  mov ecx, copy_vers

  push  4                        ; SYS_write
  pop eax
  push  2                        ; STDERR
  pop ebx
  ; Print copyright notice, version and internal name
  mov ecx, copy_vers
  push end_copy - copy_vers
  pop edx
  int 0x80

.no_error:
  mov ebx, eax                   ; error from syscall
  push 1                         ; SYS_exit
  pop eax
  int 0x80

; ==============================================================================
; VECTORS DEFINITION
; ==============================================================================

; Size of the vectors
vect_size equ 5

; The magics vector (6 × 2 byte)
magics:
;        lzop,    lz4,     xz,  bzip2,   zstd,   gzip
  dw   0x4c89, 0x2204, 0x37fd, 0x5a42, 0xb528, 0x8b1f

; The strings vector (5 × 5 byte)
paths:
        db  "lzop", 0
        db  "lz4", 0,0
        db  "xz", 0,0,0
        db  "bz", 0,0,0
        db  "zstd", 0
cmdstr: db  "/bin/"
gzpstr: db  "gunzip",0,0             ; "/bin/cat" + "zstd" + '\0' = 13 bytes

copy_vers:  db  "(c) github/robang74/uzpexec"                    ;  27 |  27
%ifdef  _HAS_PROVIDER
provider :  db  0x20, "12345678", 0x0a                           ;  10 |   -
%else
micro_ver:  db  0x20, 0x20, 0x20, 0x0a                           ;   - |   4
%endif
end_copy :
%ifndef _HAS_PROVIDER
    times 6 db  0                                                ;   - |   6
%endif
file_desc:  db  "/proc/self/fd/9", 0                             ;  16 |  16
cmd_flag :  db  "-dc", 0                                         ;   3 |   3

; ==============================================================================
; PADDING: Aligned exactly to 512 bytes
; ==============================================================================
file_end:                        ; Physical end of the binary file!
times (512 - ($ - $$)) db 0      ; Padding for 512 bytes alignement

; ==============================================================================
; BSS SECTION (RAM only, aligned to 512 bytes)
; ==============================================================================
section .bss align=8
bss_start equ $$ + 512

buf       equ bss_start          ; Only variable needed besides the buffer
bss_end   equ buf + 3584         ; buffer and binary in the same 4Kb memory page

