; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; =============================================================================
; uzcat - Universal decompressor cat
; Drop-in replacement for /bin/zcat that auto-detects compression format
; and delegates to the appropriate decompressor (or /bin/cat for plain files)
;
; Usage: uzcat < compressed_file > uncompressed_output
;        uzcat -f < file    (ignores -f flag, always behaves like "zcat -f")
;
; Supported formats: gzip, xz, lzip, bzip2, lz4, lzop, lzfs, zstd, lrzip
; Fallback: /bin/cat (transparent passthrough)
;
; Architecture: pipe+fork+exec
;   1. Parent reads first 4 bytes from stdin for magic detection
;   2. Parent determines decompressor, stores in .data variable
;   3. Parent creates pipe, forks
;   4. Child: dup2 pipe->stdin, execve decompressor (reads .data for cmd)
;   5. Parent: writes first 4 bytes to pipe, pumps rest of stdin
; =============================================================================

BITS 32
BASE_ADDR equ 0x08048000       ; Loading base definition
org BASE_ADDR

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0   ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                 ; Padding for e_ident
  dw 2                         ; e_type (Executable)
  dw 3                         ; e_machine (Intel 80386)
  dd 1                         ; e_version
  dd main_start                ; e_entry (The starting point of our code)
  dd phdr - elf_header         ; e_phoff (Offset of the Program Header Table)
  dd 0                         ; e_shoff (No Section Header Table, saving bytes)
  dd 0                         ; e_flags
  dw 52                        ; e_ehsize (Size of this header)
  dw 32                        ; e_phentsize (Size of a Program Header entry)
  dw 1                         ; e_phnum (Only one segment needed)
  ; ----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  ;
  dw 0, 0, 0                   ; Section info (zeroed out, reclamable)
  ;
  ; ASSUMPTIONS CHECK
  ;
  ; Using memfd_create() and execvat() requires a Linux kernel >= 3.19 and under
  ; this constraint no any ELF loader will complain about these six-0's missing.
  ; ----------------------------------------------------------------------------

phdr:
  dd 1                         ; p_type (PT_LOAD - Segment to load)
  dd 0                         ; p_offset
  dd BASE_ADDR                 ; p_vaddr (Virtual address in memory)
  dd BASE_ADDR                 ; p_paddr
  dd file_end - elf_header     ; p_filesz (Size of the code within the file)
  dd  bss_end - elf_header     ; p_memsz (Size of the code within memory)

  ; ----------------------------------------------------------------------------
  dd 7                         ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                    ; p_align (Standard page alignment)

  ; Security-by-Design VS Security-by-Subtraction

  ; Because uzpexec contains no input parsing logic that could be corrupted and
  ; its fixed 512-byte read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector. They are 1024 in aarm64 binary.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; CODE
; ==============================================================================
main_start:
  ; Parse argv to check for -f flag (ignore it, we always behave like zcat -f)
  pop eax                     ; argc
  pop ebx                     ; argv[0] = program name
  dec eax
  jz .read_magic              ; no args, proceed to read magic

  ; Check if argv[1] is "-f"
  pop ecx                     ; argv[1]
  cmp word [ecx], 0x662d      ; "-f" little-endian
  je .read_magic
  push ecx                    ; --> m::stack { "-f", 0 }

.read_magic:
  ; Read first 4 bytes from stdin for magic detection
  ; MUST happen BEFORE fork so child inherits correct file position
  push 3                      ; SYS_read
  pop eax
  xor ebx, ebx                ; stdin = 0
  mov ecx, buf
  mov edx, 4
  int 0x80

  cmp eax, 4
  jl .use_cat                 ; less than 4 bytes, use cat

  ; Determine decompressor from magic
  mov eax, [buf]
  call find_decompressor      ; returns EAX = pointer to decompressor string
  jmp .store_cmd

.use_cat:
  mov eax, catcmd

.store_cmd:
  mov edi, eax                ; store BEFORE fork (child inherits via COW)

  ; Create pipe: pipefd[2] on stack
  sub esp, 8
  mov ebx, esp                ; ebx = pipefd array
  push 42                     ; SYS_pipe
  pop eax
  int 0x80
  test eax, eax
  js exit_error

  ; Fork
  push 2                      ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz child                    ; FORCE near jump, child has EAX=0

; ==============================================================================
; PARENT PROCESS
; ==============================================================================
parent:
  ; Close read end of pipe
  push 6                      ; SYS_close
  pop eax
  mov ebx, [esp]              ; pipefd[0]
  int 0x80

  ; Write first 4 bytes (already in buf) to pipe
  push 4                      ; SYS_write
  pop eax
  mov edx, eax                ; = 4
  mov ebx, [esp+4]            ; pipefd[1]
  mov ecx, buf
  int 0x80

.pump_loop:
  ; Read from stdin
  mov eax, 3                  ; SYS_read
  xor ebx, ebx                ; stdin
; mov ecx, buf                ; already set
  mov edx, 512                ; buffer size
  int 0x80
  test eax, eax
  jle .done                   ; EOF or error

  ; Write to pipe
  mov edx, eax                ; bytes read
  push 4                      ; SYS_write
  pop eax
  mov ebx, [esp+4]            ; pipefd[1]
  int 0x80
  jmp .pump_loop

.done:
  ; Close write end of pipe
  push 6                      ; SYS_close
  pop eax
  mov ebx, [esp+4]            ; pipefd[1]
  int 0x80

  ; Wait for child
  push 7                      ; SYS_waitpid
  pop eax
  xor ebx, ebx
  dec ebx                     ; -1 = any child
  xor ecx, ecx                ; status = NULL
  xor edx, edx                ; options = 0
  int 0x80

  ; Exit with child's status
  mov ebx, eax
  and ebx, 0xFF00
  shr ebx, 8                  ; extract exit status
  push 1                      ; SYS_exit
  pop eax
  int 0x80

; ==============================================================================
; CHILD PROCESS
; ==============================================================================
child:
  ; Close write end of pipe
  mov al, 6                   ; SYS_close
  mov ebx, [esp+4]            ; pipefd[1]
  int 0x80

  ; Dup2 read end to stdin
  push 63                     ; SYS_dup2
  pop eax
  mov ebx, [esp]              ; pipefd[0]
  xor ecx, ecx                ; stdin = 0
  int 0x80

  ; Close original read end
  push 6                      ; SYS_close
  pop eax
; mov ebx, [esp]              ; pipefd[0]
  int 0x80

  ; Get selected decompressor (inherited from parent via COW)
  mov ebx, edi
  test ebx, ebx
  jnz .exec_it
  mov ebx, catcmd             ; fallback if somehow zero

.exec_it:
  ; Execve the decompressor
  push 11                     ; SYS_execve
  pop eax
  ; ebx = command path already
  push 0
  mov ecx, esp                ; argv = [NULL]
  xor edx, edx                ; envp = NULL (inherit from parent)
  int 0x80

  ; If execve fails, fall through to error

; ==============================================================================
; ERROR HANDLING
; ==============================================================================
exit_error:
  mov eax, 1                  ; SYS_exit
; mov ebx, 1                  ; exit code 1
  int 0x80

; ==============================================================================
; FIND DECOMPRESSOR
; Input: EAX = magic number (first 4 bytes of file, little-endian)
; Output: EAX = pointer to decompressor command string (catcmd if no match)
; ==============================================================================
find_decompressor:
  push ecx
  push edx
  mov ecx, magic_count
  mov edx, magics
  mov esi, paths
  
.loop:
  cmp ax, [edx]       ; confronta solo i primi 2 byte
  je .found
  add edx, 2          ; salta di 2 byte (dword)
  add esi, 14
  loop .loop
  
  mov eax, catcmd
  jmp .done
  
.found:
  mov eax, esi
  
.done:
  pop edx
  pop ecx
  ret

; ==============================================================================
; DATA SECTION
; ==============================================================================
section .data

; Vettore magic numbers (8 × 2 byte)
magics:
;        gzip,     xz,   lzip,  bzip2,    lz4,   lzop,   lzfs,   zstd
    dw 0x8b1f, 0x37fd, 0x5a4c, 0x5a42, 0x4d18, 0x4c89, 0x7a6c, 0xb528
magic_count equ 8

; Vettore stringhe (9 × 14 byte), padding con 0
paths:
    db "/bin/zcat", 0, 0, 0, 0
    db "/bin/xzcat", 0, 0, 0
    db "/bin/lzcat", 0, 0, 0
    db "/bin/bzcat", 0, 0, 0
    db "/bin/lz4cat", 0, 0
    db "/bin/lzopcat", 0
    db "/bin/lzfscat", 0
    db "/bin/zstdcat", 0

catcmd:
    db "/bin/cat", 0

; ==============================================================================
; FILE END
; ==============================================================================
file_end:

; ==============================================================================
; BSS SECTION (RAM only)
; ==============================================================================
section .bss

buf:
  resb 516              ; 512 byte buffer + 4 bytes for magic

bss_end:
