; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; =============================================================================
; RATIONALE
;
; Some embedded systems cannot rely on busybox seamless uncompression feature
; and not going to receive a firmware upgrade. In this condition they can use
; upzexec only with gzip compressed carryload, which is going to cover almost
; all the cases. However, gzip/zcat cannot cover all the scenarios. Hence the
; uzcat as a standalone static assembler micro-utility can provide the format
; flexibility otherwise unleveraged.  This uzcat is a specific implementation
; for uzpexec, and its name is not conflicting with an already installed zcat
; =============================================================================

BITS 32
BASE_ADDR equ 0x08048000       ; Loading base definition
org BASE_ADDR

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0   ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                 ; Padding for e_ident
  dw 2                         ; e_type (Executable)
  dw 3                         ; e_machine (Intel 80386)
  dd 1                         ; e_version
  dd main_start                ; e_entry (The starting point of our code)
  dd phdr - elf_header         ; e_phoff (Offset of the Program Header Table)
  dd 0                         ; e_shoff (No Section Header Table, saving bytes)
  dd 0                         ; e_flags
  dw 52                        ; e_ehsize (Size of this header)
  dw 32                        ; e_phentsize (Size of a Program Header entry)
  dw 1                         ; e_phnum (Only one segment needed)
  ; ----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  ;
  dw 0, 0, 0                   ; Section info (zeroed out, reclamable)
  ;
  ; ----------------------------------------------------------------------------

phdr:
  dd 1                         ; p_type (PT_LOAD - Segment to load)
  dd 0                         ; p_offset
  dd BASE_ADDR                 ; p_vaddr (Virtual address in memory)
  dd BASE_ADDR                 ; p_paddr
  dd file_end - elf_header     ; p_filesz (Size of the code within the file)
  dd  bss_end - elf_header     ; p_memsz (Size of the code within memory)

  ; ----------------------------------------------------------------------------
  dd 7                         ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                    ; p_align (Standard page alignment)

  ; Security-by-Design VS Security-by-Subtraction

  ; Because uzcat contains no input parsing logic that could be corrupted and
  ; its fixed size read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; PREDEFINED VALUE
; ==============================================================================

; Vettore magic numbers (8 × 2 byte)
magics:
;      gzip,     xz,   lzip,  bzip2,    lz4,   lzop,   lzfs,   zstd
  dw 0x8b1f, 0x37fd, 0x5a4c, 0x5a42, 0x4d18, 0x4c89, 0x7a6c, 0xb528
magic_count equ 8

; Vettore stringhe (9 × 14 byte), padding con 0
paths:
  db "/bin/zcat", 0, 0, 0, 0
  db "/bin/xzcat", 0, 0, 0
  db "/bin/lzcat", 0, 0, 0
  db "/bin/bzcat", 0, 0, 0
  db "/bin/lz4cat", 0, 0
  db "/bin/lzopcat", 0
  db "/bin/lzfscat", 0
  db "/bin/zstdcat", 0
catcmd:
  db "/bin/cat", 0, 0

; ==============================================================================
; CODE
; ==============================================================================
main_start:
  ; Parse argv to check for -f flag (ignore it, we always behave like zcat -f)
  pop eax                     ; argc
  pop ebx                     ; argv[0] = program name
  dec eax
  jz .read_magic              ; no args, proceed to read magic

  ; Check if argv[1] is "-f"
  pop ecx                     ; argv[1]
  push ecx                    ; put it back in the stack
  cmp word [ecx], 0x662d      ; compare with "-f"
  je .use_cat                 ; uzpexec uses "-f" in a specific manner

.read_magic:
  ; Read first 4 bytes from stdin for magic detection
  ; MUST happen BEFORE fork so child inherits correct file position
  push 3                      ; SYS_read
  pop eax
  xor ebx, ebx                ; stdin = 0
  mov ecx, buf
  mov edx, 4
  int 0x80
  cmp eax, 4
  jl .use_cat                 ; less than 4 bytes, use cat

  ; Determine decompressor from magic
  mov eax, [buf]
  call find_decompressor      ; returns EAX = pointer to decompressor string
  jmp .store_cmd

.use_cat:
  push dword 1
  push dword 0
  jmp parent.do_cat

.store_cmd:
  mov edi, eax                ; store BEFORE fork (child inherits via COW)

  ; Create pipe: pipefd[2] on stack
  sub esp, 8
  mov ebx, esp                ; ebx = pipefd array
  push 42                     ; SYS_pipe
  pop eax
  int 0x80
  test eax, eax
  js do_exit

  ; Fork
  push 2                      ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz child                    ; FORCE near jump, child has EAX=0

; ==============================================================================
; PARENT PROCESS
; ==============================================================================
parent:
  ; Close read end of pipe
%ifdef _DO_CLOSE
  push 6                      ; SYS_close
  pop eax
  mov ebx, [esp]              ; pipefd[0]
  int 0x80
%endif

.do_cat:                      ; cat *.iso | ./uzcat -f  | dd bs=1M of=/dev/null
                              ; dd: 93 MB (88 MiB) copied, 0.0638537s, 1.5 GB/s
  ; Write first 4 bytes (already in buf) to pipe
  push 4                      ; bytes already read, to write
  pop eax

  mov ecx, buf                ; set once and keep untouched

.pump_loop:
  ; Write to pipe
  mov ebx, [esp+4]            ; pipefd[1]
  mov edx, eax                ; bytes already read, to write

  push 4                      ; SYS_write
  pop eax
  int 0x80

  ; Read from stdin
  xor ebx, ebx                ; stdin
  mov edx, 3584               ; buffer size

  push 3                      ; SYS_read
  pop eax
  int 0x80

  test eax, eax
  jz .done                    ; check for EOF
%ifdef _DO_EINTR
  cmp eax, -4                 ; check for -EINTR (if any, ever)
  je .pump_loop               ; continue
%endif
  js do_exit
  jmp .pump_loop              ; continue
  
.done:
  mov eax, [esp]
  test eax, eax
  jz do_exit                  ; after do_cat, do_exit

  ; Close the writing pipe to send EOF to the child
  push 6                      ; SYS_close
  pop eax
  mov ebx, [esp+4]            ; pipefd[1]
  int 0x80

  ; Wait for child
  push 7                      ; SYS_waitpid
  pop eax
  xor ebx, ebx
  dec ebx                     ; -1 = any child
  xor ecx, ecx                ; status = NULL
  xor edx, edx                ; options = 0
  int 0x80

  ; Exit with child's status
  mov ebx, eax
  and ebx, 0xFF00
  shr ebx, 8                  ; extract exit status
  push 1                      ; SYS_exit
  pop eax
  int 0x80

; ==============================================================================
; CHILD PROCESS
; ==============================================================================
child:
  ; Close write end of pipe
  mov al, 6                   ; SYS_close
  mov ebx, [esp+4]            ; pipefd[1]
  int 0x80

  ; Dup2 read end to stdin
  push 63                     ; SYS_dup2
  pop eax
  mov ebx, [esp]              ; pipefd[0]
  xor ecx, ecx                ; stdin = 0
  int 0x80

  ; Close original read end
%ifdef _DO_CLOSE
  push 6                      ; SYS_close
  pop eax
; mov ebx, [esp]              ; pipefd[0]
  int 0x80
%endif

  ; Get selected decompressor
  mov ebx, edi

.exec_it:
  ; Execve the decompressor
  push 11                     ; SYS_execve
  pop eax
  ; ebx = command path already
  push 0
  mov ecx, esp                ; argv = [NULL]
  xor edx, edx                ; envp = NULL (inherit from parent)
  int 0x80

  ; If execve fails, fall through to error

; ==============================================================================
; ERROR HANDLING
; ==============================================================================
do_exit:
  mov ebx, eax                ; error from syscall
  push 1                      ; SYS_exit
  pop eax
  int 0x80

; ==============================================================================
; FIND DECOMPRESSOR
; Input: EAX = magic number (first 4 bytes of file, little-endian)
; Output: EAX = pointer to decompressor command string (cat, if no match)
; ==============================================================================
find_decompressor:
  push ecx
  push edx
  mov ecx, magic_count
  mov edx, magics
  mov esi, paths
  
.loop:
  cmp ax, [edx]       ; confronta solo i primi 2 byte
  je .found
  add edx, 2          ; salta di 2 byte (dword)
  add esi, 14
  loop .loop

%if 0                 ; useless, cat_cmd is set at the end of loop of strings 
  push 0
  pop eax
  jmp .done
%endif

.found:
  mov eax, esi
  
.done:
  pop edx
  pop ecx
  ret

; ==============================================================================
; PADDING: Aligned exactly to 512 bytes
; ==============================================================================
file_end:                       ; Physical end of the binary file!
;times (512 - ($ - $$)) db 0    ; Padding for 512 bytes alignement

; ==============================================================================
; BSS SECTION (RAM only, aligned to 512 bytes)
; ==============================================================================
section .bss align=8
bss_start equ $$ + 512

buf       equ bss_start         ; Only variable needed besides the buffer
bss_end   equ buf + 3584        ; buffer and binary in the same 4Kb memory page

