; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; ==============================================================================

BITS 32
org 0x08048000

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0   ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                 ; Padding for e_ident
  dw 2                         ; e_type (Executable)
  dw 3                         ; e_machine (Intel 80386)
  dd 1                         ; e_version
  dd main_start                ; e_entry (The starting point of our code)
  dd phdr - elf_header         ; e_phoff (Offset of the Program Header Table)
  dd 0                         ; e_shoff (No Section Header Table, saving bytes)
  dd 0                         ; e_flags
  dw 52                        ; e_ehsize (Size of this header)
  dw 32                        ; e_phentsize (Size of a Program Header entry)
  dw 1                         ; e_phnum (Only one segment needed)
  ;-----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  dw 0, 0, 0                   ; Section info (zeroed out)
  ; Finally managed to suck more bits out from nowhere to rescue these six 0s

phdr:
  dd 1                         ; p_type (PT_LOAD - Segment to load)
  dd 0                         ; p_offset
  dd 0x08048000                ; p_vaddr (Virtual address in memory)
  dd 0x08048000                ; p_paddr
  dd file_end - elf_header     ; p_filesz (Size of the code within the file)
  dd bss_end - elf_header      ; p_memsz (Size of the code within memory)

  ;-----------------------------------------------------------------------------
  dd 7                         ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                    ; p_align (Standard page alignment)

  ; Security-by-Design VS Security-by-Subtraction

  ; Because uzpexec contains no input parsing logic that could be corrupted and
  ; its fixed 512-byte read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; upexec CODE (Execution starts here)
; ==============================================================================
main_start:
  ; This would be the main() in a C-language sourcemain_start
  ; Save original argv and calculate envp from the initial stack layout
  ; Stack: [argc] [argv[0]] ... [argv[N]] [NULL] [envp...]
  pop eax                      ; argc (was [esp])
  mov esi, esp                 ; ESI = argv
  lea ebp, [esi+eax*4+4]       ; EBP = envp (callee-saved!)

  ; 0. Checking argv[0] to open input (itself or stdin)
  mov ebx, [esi]               ; CVE-2021-4034, pre-5.18
                               ; Tiny can't cover LK bugs
                               ; It will fail soon after
; push esi                     ; Save ESI (argv) on the stack
  ; ============================================================================

  ; 1. Try to open itself file by argv[0] (CVE-2021-4034, ends here)
; mov ebx, [esi]               ; EBX = argv[0]
  xor ecx, ecx                 ; O_RDONLY
  push 5                       ; SYS_open
  pop eax
  int 0x80
  mov edi, eax                 ; Move fd in EDI to save it for later

  ; 2. Try to open the memfd, as first operation
  mov eax, 356                 ; SYS_memfd_create
  mov ebx, filename            ; Linux requires a name here
  push ebx                     ; filename
  push 1                       ; MFD_CLOEXEC
  pop ecx
  int 0x80
; mov [memfd], eax             ; Save the memfd in RAM
  push eax                     ; Save the memfd on the stack

  ; 3. Try to read from the file the 1st block + 4 bytes to check the carryload
  mov ecx, buf
  mov edx, 516                 ; read size (512+4), 32-bit aligned
.skip_loop:
  push 3                       ; SYS_read
  pop eax
  mov ebx, edi                 ; input fd
  int 0x80
  test eax, eax
  js .stdin                    ; if read fails, read STDIN
  jz .stdin                    ; if premature EOF, read STDIN
  sub edx, eax
  jnz .skip_loop
  jmp .fork_now                ; EDI = fd at +516 bytes (**)

.stdin:
%ifdef _NO_STDIN
  jmp exit_error               ; single point of detour
%else
  xor edi, edi                 ; EDI = 0 (STDIN)
%endif

.fork_now:
  ; 4a. File pointer set
  push 19                      ; SYS_lseek
  pop eax
  mov ecx, 512                 ; offset = 512
  xor edx, edx                 ; SEEK_SET = 0
  int 0x80
  ; 4b. Fork the process
  push 2                       ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz child                     ; the child jump to its routine

  ; ============================================================================
  ; PARENT PROCESS
  ; ============================================================================
parent:
  ; 1p. The parent waits for the child completes zcat writing in memfd
  xor ecx, ecx
  xor edx, edx
  xor ebx, ebx
  dec ebx                      ; -1
  push 7                       ; SYS_waitpid
  pop eax
  int 0x80

  ; 2p. Closing the real file once read in full, also for safety,
  ;     but fd is RD_ONLY so we can save bytes here, avoiding it.
  ; test edi, edi
  ; jz .rewind_memfd
  ; push 6                       ; SYS_close
  ; pop eax
  ; mov ebx, edi
  ; int 0x80

.rewind_memfd:
  ; 3p. Rewind memfd at the starting point to check for the shebang script
  push 19                      ; SYS_lseek
  pop eax
; mov ebx, [memfd]             ;
  pop ebx                      ; [memfd]
  xor ecx, ecx                 ; offset = 0
  xor edx, edx                 ; SEEK_SET = 0
  int 0x80

  ; 4p. Read the first uncompressed 4 bytes (just two for the shebang)
  push 3                       ; SYS_read
  pop eax
  mov ecx, buf                 ;
  push 4                       ;
  pop edx                      ; count = 4
  int 0x80

  ; 5p. Check about ELF magic chars sequence (\x7FELF)
  ;     A 32-bit comparison is shorter, safer and faster
  ;     compared with checking for the shebang (optional)
  cmp dword [ecx], 0x464c457f  ; Match Little-Endian
  jz .execute_elf              ; If ELF, do execve()

  ; ----------------------------------------------------------------------------
  ; SCRIPT MODE
  ; ----------------------------------------------------------------------------
  ; 1s. Rewind memfd at the starting point to pass it to the shell
  push 19                      ; SYS_lseek
  pop eax
; mov ebx, [memfd]
  xor ecx, ecx                 ; offset = 0
  xor edx, edx                 ; SEEK_SET = 0
  int 0x80

  ; 2s. Connect the memfd to the shell STDIN (fd 0)
  push 63                      ; SYS_dup2
  pop eax
; mov ebx, [memfd]
  xor ecx, ecx                 ; 0 = stdin
  int 0x80

  ; 3s. Spawns a /bin/sh whose STDIN is piped to zcat, passing original argvs
  push 11                      ; SYS_execve
  pop eax
  ; pushing on current argv[0] do_script
  mov ebx, do_script           ; script interpreter

  ; Safeguard: if argc is 0 <-- No, the issue was argv=NULL, SIGSEGV solves
  ; Therefore the branch "no_args" would never traversed and can be removed

  ; In-place stack manipulation using ESP (argv is at [esp]):
  mov dword [esp+4], dual_dash ; overwrite original argv[] with "--"
  mov dword [esp+0], stdin_arg ; overwrite original argv[] with "-s"
  lea ecx,  [esp-8]            ; original arguments argv[1] ... [n]
  push stdin_arg               ; pushing "-s"
  push dword ebx

  ; basic operations for calling the execve()
  mov edx, ebp                 ; envp (intact from main_start)
  int 0x80
; jmp exit_error               ; eventually will fail later

  ; ----------------------------------------------------------------------------
  ; ELF BINARY MODE
  ; ----------------------------------------------------------------------------
.execute_elf:
  ; 1e. Execute the ELF binary using a Linux specific syscall
  mov eax, 358                 ; SYS_execveat
; mov ebx, [memfd]             ; EBX = memfd
  push 0                       ; "" on the stack
  mov ecx, esp                 ; ECX points to ""
  mov edx, esi                 ; EDX = argv (original)
  mov esi, ebp                 ; ESI = envp (original)
  mov edi, 0x1000              ; EDI = AT_EMPTY_PATH
  int 0x80
  jmp exit_error

; ============================================================================
; CHILD PROCESS
; ============================================================================
child:
  ; 1c. 1st dup2: connect input (EDI) to STDIN (0) for both modes
  push 63                      ; SYS_dup2
  pop eax
  mov ebx, edi                 ; FD di input
  xor ecx, ecx                 ; 0 = stdin
  int 0x80

  ; 2c. 2nd dup2: connect output to STDOUT (1) of the child which is MEMFD
  push 63                      ; SYS_dup2
  pop eax
; mov ebx, [memfd]             ; zcat writes in memfd
  pop ebx                      ; shared stack but indipendent after fork()
  inc ecx                      ; 1 = stdout
  int 0x80
  test eax, eax
  js exit_error

  ; 3c. Execute zcat passing "-f" when reading from the STDIN (**)
  push 11                      ; SYS_execve
  pop eax
  mov ebx, zcat_path           ;
  push 0                       ; end of envp/argv
  test edi, edi

  jnz .no_force                ; only on STDIN
  push force_arg               ; "-f"
.no_force:

  push zcat_path               ; argv[0] is "/bin/zcat"
  mov ecx, esp                 ; argv[1...]
  xor edx, edx                 ; envp null
  int 0x80

  ; ============================================================================
exit_error:
; test ebx, ebx
; jnz exit_now

  ; Print copyright notice, version and internal name
  push zcat_path - copy_vers    ; bytes to write --> stack
  pop edx                       ; bytes to write <-- stack
  mov ecx, copy_vers
  mov byte [ecx + edx - 1], 10  ; line feed
  push  4                       ; SYS_write
  pop eax
  push  2                       ; stderr
  pop ebx
  int 0x80

; exit_now:
; xor ebx, ebx
; inc ebx                       ; Exit code 1
  push 1
  pop eax
  int 0x80

; ==============================================================================
; COMPACT DATA SECTION (appended to code)
; ==============================================================================
; filename can be changed by sed up to 7 chars + ending \0
; zcat -f is cat when input isn't gzip, options up to -6c\0
; /bin/zcat can be changed by sed up to 41 chars + ending \0
; - for example: /usr/local/bin/xzcat is 20 chars + ending \0
; in do_script mode the 2 paths shrink to 20 chars + ending \0
; eof_strng helps to find the EOF, and where \0 padding starts
;                                                                   LN | FD | SH
copy_vers:  db "(c) github/robang74 v0.91 "                       ; 26 | 26 | 26
filename :  db      "uzpexec", 0                                  ;  8 |  8 |  8
zcat_path:  db         "/bin/zcat",  0,0,0, 0,0,0,0, 0,0,0,0, 0   ; 21 | 42 | 21
; following fields are conditionally overwritable, do unions      : --------- 55
do_script:  db      "/bin/sh", 0, 0, 0,0,0, 0,0  ; for sh         ; 14 |  - | 18
eof_tests:  db "U238",                           ; for tests      :  4 |  - |  -
stdin_arg:  db "-s", 0                           ; for sh         :  3 |  - |  3
dual_dash:  db "--", 0                           ; for sh         :  3 |  - |  3
force_arg:  db "-f", 0                           ; for zcat       :  3 |  3 |  3
;              |<-- 8 chars -->|<- +8c ->|                        : --------- 27
                                                                  ; 82 (tot.) 82
; ==============================================================================
; PADDING: Aligned exactly to 512 bytes (dd skip=1)
; ==============================================================================
file_end:                       ; Physical end of the binary file!
times (512 - ($ - $$)) db 0     ; Padding to 512 bytes for skip=1

; ==============================================================================
; BSS SECTION (RAM only, aligned to 512 bytes)
; ==============================================================================
bss_start equ $$ + 512

buf:      equ bss_start         ; Only variable needed besides the buffer
bss_end:  equ buf + 516         ; Reserve 512 + 4 bytes for the buffer

