; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; ==============================================================================

BITS 32
org 0x08048000

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0   ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                 ; Padding for e_ident
  dw 2                         ; e_type (Executable)
  dw 3                         ; e_machine (Intel 80386)
  dd 1                         ; e_version
  dd main_start                ; e_entry (The starting point of our code)
  dd phdr - elf_header         ; e_phoff (Offset of the Program Header Table)
  dd 0                         ; e_shoff (No Section Header Table, saving bytes)
  dd 0                         ; e_flags
  dw 52                        ; e_ehsize (Size of this header)
  dw 32                        ; e_phentsize (Size of a Program Header entry)
  dw 1                         ; e_phnum (Only one segment needed)
  ;-----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  dw 0, 0, 0                   ; Section info (zeroed out)
  ; Finally managed to suck more bits out from nowhere to rescue these six 0s

phdr:
  dd 1                         ; p_type (PT_LOAD - Segment to load)
  dd 0                         ; p_offset
  dd 0x08048000                ; p_vaddr (Virtual address in memory)
  dd 0x08048000                ; p_paddr
  dd file_end - elf_header     ; p_filesz (Size of the code within the file)
  dd bss_end - elf_header      ; p_memsz (Size of the code within memory)

  ;-----------------------------------------------------------------------------
  dd 7                         ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                    ; p_align (Standard page alignment)

  ; Security-by-Design VS Security-by-Subtraction

  ; Because uzpexec contains no input parsing logic that could be corrupted and
  ; its fixed 512-byte read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; upexec CODE (Execution starts here)
; ==============================================================================
main_start:
  ; This would be the main() in a C-language sourcemain_start
  ; Save original argv and calculate envp from the initial stack layout
  ; Stack: [argc] [argv[0]] ... [argv[N]] [NULL] [envp...]
  pop eax                      ; argc (was [esp])
  mov esi, esp                 ; ESI = argv
  lea ebp, [esi+eax*4+4]       ; EBP = envp (callee-saved!)

  ; Checking argv[0] to open input (itself or stdin)
  mov ebx, [esi]               ; CVE-2021-4034, pre-5.18
                               ; Tiny can't cover LK bugs
; push esi                     ; Save ESI (argv) on the stack
  ; ============================================================================

  ; 0. Creazione incondizionata del memfd
  mov eax, 356                 ; SYS_memfd_create
  mov ebx, filename            ; Nome del file fittizio
  push ebx                     ; filename
  push 1                       ; MFD_CLOEXEC
  pop ecx
  int 0x80
  mov [memfd], eax             ; Salva l'FD del memfd

  ; 1. Tentativo di apertura di argv[0]
  mov ebx, [esi]               ; EBX = argv[0]
  xor ecx, ecx                 ; O_RDONLY
  push 5                       ; SYS_open
  pop eax
  int 0x80
  mov edi, eax                 ; Sposta l'FD in EDI per preservarlo

  ; 2. Verifica se l'apertura ha avuto successo tramite lettura dell'header
  mov ecx, buf
  mov edx, 516                 ; read size (512+4), 32-bit aligned
.skip_loop:
  push 3                       ; SYS_read
  pop eax
  mov ebx, edi                 ; input fd
  int 0x80
  test eax, eax
  js .stdin                    ; Se errore, passa a STDIN
  jz .stdin                    ; Se EOF prematuro, passa a STDIN
  sub edx, eax
  jnz .skip_loop
  jmp .fork_now                ; Successo: EDI contiene l'FD del file pronto (+516 byte)

.stdin:
%ifdef _NO_STDIN
  jmp exit_error               ; single point of detour
%else
  xor edi, edi                 ; EDI = 0 (STDIN)
%endif

.fork_now:
  ; 3. File pointer set
  push 19                      ; SYS_lseek
  pop eax
  mov ecx, 512                 ; offset = 512
  xor edx, edx                 ; SEEK_SET = 0
  int 0x80
  ; 3. Fork del processo
  push 2                       ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz child                     ; Se figlio, salta al blocco child

  ; ============================================================================
  ; PARENT PROCESS
  ; ============================================================================
parent:
  ; Il genitore attende che il figlio (zcat) completi il dump nel memfd
  xor ecx, ecx
  xor edx, edx
  xor ebx, ebx
  dec ebx                      ; -1
  push 7                       ; SYS_waitpid
  pop eax
  int 0x80

  ; Se abbiamo aperto un file reale, chiudiamo l'FD non più necessario
  test edi, edi
  jz .rewind_memfd
  push 6                       ; SYS_close
  pop eax
  mov ebx, edi
  int 0x80

.rewind_memfd:
  ; Rewind del memfd all'inizio per lo sniffing dei magic bytes
  push 19                      ; SYS_lseek
  pop eax
  mov ebx, [memfd]             ;
  xor ecx, ecx                 ; offset = 0
  xor edx, edx                 ; SEEK_SET = 0
  int 0x80

  ; Lettura dei primi 4 byte
  push 3                       ; SYS_read
  pop eax
  mov ecx, buf                 ;
  push 4                       ;
  pop edx                      ; count = 4
  int 0x80

  ; Verifica la firma dell'ELF (\x7FELF)
  cmp dword [buf], 0x464c457f  ; Match Little-Endian
  jz .execute_elf              ; Se ELF, salta alla transizione diretta

  ; ----------------------------------------------------------------------------
  ; SCRIPT MODE: Gestione interpretata via /bin/sh
  ; ----------------------------------------------------------------------------
  ; Riporta il memfd a 0 affinché la shell possa leggerlo dall'inizio
  push 19                      ; SYS_lseek
  pop eax
  mov ebx, [memfd]
  xor ecx, ecx
  xor edx, edx
  int 0x80

  ; Collega il memfd allo STDIN (fd 0) per l'interprete
  push 63                      ; SYS_dup2
  pop eax
  mov ebx, [memfd]
  xor ecx, ecx                 ; 0 = stdin
  int 0x80

  ; ----------------------------------------------------------------------------
  ; Spawns a /bin/sh whose STDIN is piped to zcat, passing along original argvs
  ; ----------------------------------------------------------------------------
  push 11                      ; SYS_execve
  pop eax
                 ; pushing on current argv[0] do_script
  mov ebx, do_script           ; script interpreter

  ; Safeguard: if argc is 0 <-- No, the issue was argv=NULL, SIGSEGV solves
  ; Therefore the branch "no_args" would never traversed and can be removed

  ; In-place stack manipulation using ESP (argv is at [esp]):
  mov dword [esp + 4], dual_dash   ; overwrite original argv[] with "--"
  mov dword [esp + 0], stdin_arg   ; overwrite original argv[] with "-s"
  lea ecx,  [esp - 8]           ; original arguments argv[1] ... [n]
  push stdin_arg               ; pushing "-s"
  push dword ebx

  ; basic operations for calling the execve()
  mov edx, ebp                 ; envp (intact from main_start)
  int 0x80
  jmp exit_error
  ; ----------------------------------------------------------------------------

  ; ----------------------------------------------------------------------------
  ; ELF BINARY MODE: Esecuzione diretta nativa
  ; ----------------------------------------------------------------------------
.execute_elf:
  mov eax, 358                 ; SYS_execveat
  mov ebx, [memfd]             ; EBX = FD del memfd
  push 0                       ; Stringa vuota "" su stack
  mov ecx, esp                 ; ECX punta a ""
  mov edx, esi                 ; EDX = argv originario
  mov esi, ebp                 ; ESI = envp
  mov edi, 0x1000              ; EDI = AT_EMPTY_PATH
  int 0x80
  jmp exit_error

; ============================================================================
; CHILD PROCESS
; ============================================================================
child:
  ; 1st dup2: Direziona l'input (file posizionato o STDIN) nello STDIN del child
  push 63                      ; SYS_dup2
  pop eax
  mov ebx, edi                 ; FD di input
  xor ecx, ecx                 ; 0 = stdin
  int 0x80

  ; 2nd dup2: Connette l'output del memfd allo STDOUT del child
  push 63                      ; SYS_dup2
  pop eax
  mov ebx, [memfd]             ; Scrive nel memfd condiviso
  inc ecx                      ; 1 = stdout
  int 0x80
  test eax, eax
  js exit_error

  ; Esecuzione di zcat con l'argomento "-f" sempre attivo
  push 11                      ; SYS_execve
  pop eax
  mov ebx, zcat_path           ;
  push 0                       ; Fine envp/argv
  push force_arg               ; Forza il trattamento trasparente ("-f")
  push zcat_path               ; argv[0] per il tool
  mov ecx, esp                 ; Costruisce il vettore degli argomenti
  xor edx, edx                 ; envp nullo
  int 0x80

; ============================================================================
exit_error:
  ; Stampa della notifica d'errore/copyright
  push zcat_path - copy_vers   ;
  pop edx                      ;
  mov ecx, copy_vers           ;
  mov byte [ecx + edx - 1], 10  ;
  push 4                       ; SYS_write
  pop eax
  push 2                       ; stderr
  pop ebx
  int 0x80

  push 1                       ; Exit code 1
  pop eax
  int 0x80

; ==============================================================================
; COMPACT DATA SECTION (appended to code)
; ==============================================================================
copy_vers: db "(c) github/robang74 v0.90 "                       ;
filename : db      "uzpexec", 0                                  ;
zcat_path: db         "/bin/zcat",  0,0,0, 0,0,0,0, 0,0,0,0, 0   ;
do_script: db "/bin/sh", 0                                       ;
eof_tests: db "U238"                                             ;
stdin_arg: db "-s", 0                                            ;
dual_dash: db "--", 0                                            ;
force_arg: db "-f", 0                                            ;

; ==============================================================================
; PADDING: Allineamento perfetto a 512 byte
; ==============================================================================
file_end:
times (512 - ($ - $$)) db 0    ;

; ==============================================================================
; BSS SECTION (RAM temporary storage)
; ==============================================================================
bss_start equ $$ + 512

memfd:    equ bss_start + 0    ;
buf:      equ memfd + 4        ;
bss_end:  equ buf + 516        ;

