; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; ==============================================================================
;
; USAGE:
; - a) { cat uzpexec; gzip -c $elfbin; } > $self-extracting-executable.uzp
; - b) cp uzpexec $zelfbin; gzip -c $elfbin >> $zelfbin.uzp (the same ^^^)
; - c) { cat uzpexec | sed 's/zcat\x00/xzcat/'; xz -7c $elf; } > $elf.uxp
; - d) cat uzpexec | upexec [args] when upexec carries a gzip load
; - e) wget $url/$elf[.gz] -O- | uzpexec [args]
; - f) printf '#!/bin/sh\necho Hello World!\n' | gzip -c | {
;      f=uzpexec; sed -e 's,\x00\(/bin/sh\),\x01\1,' -i $f; $f; }
;
; ==============================================================================
;
; Fix for the 2-pipe architecture for zcat:
; - 1. Reads itself (from argv[0] or stdin)
; - 2. Discards the first 512 bytes (skips the header/loader)
; - 3. Sends the remainder to zcat via pipe
; - 4. Reads the unpacked output from zcat and loads it into an anonymous memfd
; - 5. Executes the code from the memfd
;
; Optimization #1:
; - Single pipe (input) with direct writing by design.
; - Do fork: child writes directly to MEMFD via dup2.
;
; Optimization #2:
; - Zero pipe is the highest efficient version.
; - Transparently supports argv[0] or STDIN, both.
;
; Parent:
; - open(argv[0])     → fd 3 (or stdin = 0)
; - memfd_create()    → fd 4
; - skip 512 bytes from fd 3 (read loop)
; - fork()
;
; Child:
; - dup2(fd 3, 0)  ; stdin = input (offset, already +512 bytes)
; - dup2(fd 4, 1)  ; stdout = memfd
; - execve("zcat", ["zcat", "-"], NULL)
;
; Parent:
; - waitpid(-1, ...)
; - execveat(fd 4, "", argv, envp, AT_EMPTY_PATH)
;
; ==============================================================================

BITS 32
org 0x08048000

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0  ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                ; Padding for e_ident
  dw 2                        ; e_type (Executable)
  dw 3                        ; e_machine (Intel 80386)
  dd 1                        ; e_version
  dd main_start               ; e_entry (The starting point of our code)
  dd phdr - elf_header        ; e_phoff (Offset of the Program Header Table)
  dd 0                        ; e_shoff (No Section Header Table, saving bytes)
  dd 0                        ; e_flags
  dw 52                       ; e_ehsize (Size of this header)
  dw 32                       ; e_phentsize (Size of a Program Header entry)
  dw 1                        ; e_phnum (Only one segment needed)
  ;-----------------------------------------------------------------------------
  ; Many Linux kernel ELF parsers completely ignore these 6
  ; bytes when section offset e_shoff = 0, as in this case.
  ; dw 0, 0, 0                ; Section info (zeroed out)
  ; We need to suck more bits out from void for rescuing these six zeros

phdr:
  dd 1                        ; p_type (PT_LOAD - Segment to load)
  dd 0                        ; p_offset
  dd 0x08048000               ; p_vaddr (Virtual address in memory)
  dd 0x08048000               ; p_paddr
  dd file_end - elf_header    ; p_filesz (Size of the code within the file)
  dd bss_end - elf_header     ; p_memsz (Size of the code within memory)

  ;-----------------------------------------------------------------------------
  dd 7                        ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                   ; p_align (Standard page alignment)

  ; Security by Design Versus Security by Subtraction

  ; Because uzpexec contains no input parsing logic that could be corrupted and
  ; its fixed 512-byte read loop cannot be overflowed, the writeable-executable
  ; segment offers no exploitable attack vector.

  ; Since the loader immediately forfeits control through atomic fork() / exec()
  ; or execveat() transitions that never return, an attacker cannot redirect
  ; execution to modified code before the process image is replaced.

  ; An adversary who can already write to the process memory holds sufficient
  ; privileges to inject code via ptrace or mprotect on any standard binary,
  ; which means the R+W+X flag introduces zero additional risk.

  ; WRX is the least of your troubles, but uzpexec as obscenely-powerful tool.

; ==============================================================================
; upexec CODE (Execution starts here)
; ==============================================================================
main_start:
  ; This would be the main() in a C-language sourcemain_start
  ; Save original argv and calculate envp from the initial stack layout
  ; Stack: [argc] [argv[0]] ... [argv[N]] [NULL] [envp...]
  pop eax                       ; argc (was [esp])
  mov esi, esp                  ; ESI = argv
  lea ebp, [esi+eax*4+4]        ; EBP = envp (callee-saved!)

  ; 1. Checking argv[0] to open input (itself or stdin)
  mov esi, [esi]
  test esi, esi                 ; CVE-2021-4034, pre-5.18
  jz .stdin
  cmp byte [esi], al            ; al is set to 0 here
  jz .stdin

  ; ----------------------------------------------------------------------------
  ; THE BASENAME STREAM & HARDWARE MIRROR MATCH
  ; ----------------------------------------------------------------------------
  push esi                      ; Saves the ESI register
  mov edx, esi                  ; EDX points to basename
.scan_loop:
  lodsb                         ; AL = *ESI++, by CPU
  cmp al, '/'                   ; Is there a slash in path?
  jne .check_zero               ; - N: check for a \0 char
  mov edx, esi                  ; - Y: move 1 char forward

.check_zero:
  test al, al                   ; Is this the end of argv[0]?
  jnz .scan_loop                ; - N: continue the seek loop

  ; EDX is pointing to the basename 1st char (eg. "uzpexec\0")
  ; Let's start the byte-by-byte comparison with filename var
  mov esi, edx                  ; ESI points to the basename
  mov edi, filename             ; EDI points to the filename

.strcmp_loop:
  lodsb                         ; AL = *ESI++ (basename)
  scasb                         ; Compare AL against *EDI++
  jne .not_uzpexec              ; Names differ? Go for MEMFD
  test al, al                   ; Is the end of the string?
  jnz .strcmp_loop              ; - N: continue the loop

  pop esi                       ; Restore the ESI register
  jmp .stdin                    ; Names match, go for SHELL
  ; ----------------------------------------------------------------------------

.not_uzpexec:
  ; 2. Try to open itself (embedded payload mode, only)
  xor ecx, ecx                  ; O_RDONLY
  push 5                        ; SYS_open
  pop eax
  int 0x80
; It will fail later, anyway
; test eax, eax
; js exit_error
  mov edi, eax                  ; EDI = input fd (opened file)

  ; 3. Skip the fixed 512-bytes initial block (!stdin, only self-read)
  mov ecx, buf
  mov edx, 512
.skip_loop:
  push 3                        ; SYS_read
  pop eax
  mov ebx, edi                  ; input fd
  int 0x80
  test eax, eax
  js exit_error
  jz exit_error                 ; Premature EOF
  sub edx, eax
  jnz .skip_loop
  jmp .memfd

.stdin:
  xor edi, edi                  ; EDI = stdin (0)

.memfd:
  mov ebx, filename             ; fd owner's name
  movzx edx, byte [ebx - filename + do_script]
                                ; EDX now holds the flag
  test dl, dl                   ; Is the script flag 0?
  jnz .do_script                ; - N: call the /bin/sh
                                ; - Y: exec an ELF binary
  mov eax, 356                  ; SYS_memfd_create
  push 1                        ; MFD_CLOEXEC
  pop ecx
  int 0x80
; It will fail later, anyway
; test eax, eax
; js exit_error
  mov [memfd], eax
  jmp .fork_now                 ; Try to fork

.do_script:
  ; We are using 2-bytes at the tiop of BSS buffer (buf) to save the 2 FDs
  push 42                       ; SYS_pipe
  pop eax
  mov ebx, buf                  ; EBX is pointing to a 2 words array in BBS
  int 0x80                      ; Now buf[0] = read_fd, buf[4] = write_fd

.fork_now:
  ; 5. Do a fork without do any pipe (lighter fork)
  push 2                        ; SYS_fork
  pop eax
  int 0x80
  test eax, eax
  jz child                      ; If EAX == 0, go to child process

  ; ============================================================================
  ; PARENT PROCESS
  ; ============================================================================
parent:
  test dl, dl                   ; Is it ELF mode (0)?
  jz elf_mode                   ; - Y: standard waitpid execution
                                ; - N: spawn the alt. interpreter
  ; It closes an useless pipe
  push 6                        ; SYS_close
  pop eax
  mov ebx, [buf+4]              ; write_fd
  int 0x80

  ; Aggancia il lato di lettura della pipe al proprio STDIN (fd 0)
  push 63                       ; SYS_dup2
  pop eax
  mov ebx, [buf]                ; read_fd
  xor ecx, ecx                  ; 0 = stdin
  int 0x80

  ; Esegue /bin/sh. Avendo STDIN collegato a zcat, la shell eseguirà lo script!
  push 11                       ; SYS_execve
  pop eax
  mov ebx, do_script            ; script interpreter
  push 0                        ; envp / argv finale
  push ebx                      ; argv[0]
  mov ecx, esp                  ; argv
  xor edx, edx                  ; envp = NULL
  int 0x80
  jmp exit_error

  ; The parent only needs to wait for the child (zcat) to finish decompressing
elf_mode:
  push -1
  pop ebx                       ; -1
  xor ecx, ecx
  xor edx, edx
  push 7                        ; SYS_waitpid
  pop eax
  int 0x80

  ; Closes the initial input (no longer needed in the parent), if !stdin
  test edi, edi
  jz .execute                   ; From stdin has file openedmain_start
  push 6                        ; SYS_close
  pop eax
  mov ebx, edi                  ; Closes the opened file fd
  int 0x80

.execute:
  ; 6. Execution from the memfd, which now contains the entire unpacked binary
  ; Fix argv[0] to point to our custom name in filename
  ; mov eax, filename           ; Load address of filename string
  ; mov [esi], eax              ; Overwrite original argv[0]
  ; Clean restoration of the stack before execveat to avoid EFAULT
  mov eax, 358                  ; SYS_execveat
  mov ebx, [memfd]              ; EBX = validated memfd
  push 0                        ; push empty string "" to the stack
  mov ecx, esp                  ; ECX = points to ""
  mov edx, esi                  ; EDX = intact original argv
  mov esi, ebp                  ; ESI = envp (extracted from EBP)
  mov edi, 0x1000               ; EDI = AT_EMPTY_PATH flag
  int 0x80                      ; Invoke Linux kernel to replace process
  jmp exit_error                ; execve() never returns, and we catch here
                                ; previously unchecked errors for smaller code

; ============================================================================
; CHILD PROCESS (Executes zcat by connecting existing descriptors)
; ============================================================================
child:
  ; 1st dup2: Connect input (edi) to STDIN (0) for both modes
  push 63                       ; SYS_dup2
  pop eax
  mov ebx, edi                  ; input fd (file or 0)
  xor ecx, ecx                  ; 0 = stdin
  int 0x80                      ; ECX remains 0 on return

  ; Select the correct output descriptor based on mode
  mov ebx, [memfd]              ; Default: assume ELF mode destination
  test dl, dl                   ; Is it ELF mode (0)?
  jz .do_stdout                 ; - Y: skip to stdout redirection
  mov ebx, [buf+4]              ; - N: overwrite with pipe write_fd

.do_stdout:
  ; 2nd dup2: Connect selected output (ebx) to STDOUT (1)
  push 63                       ; SYS_dup2
  pop eax
  inc ecx                       ; 1 = stdout (incremented from 0)
  int 0x80
  test eax, eax                 ; Catch deferred memfd/pipe errors here
  js exit_error

  ; Clean execution of simple zcat (zcat -)
  push 11                       ; SYS_execve
  pop eax
  mov ebx, zcat_path
  push 0
  push  dash_arg
  test edi, edi                 ; Are we reading from STDIN (edi == 0)?
  jnz .pure_zcat                ; No, it is a file, then skip '-f' push
  push force_arg

.pure_zcat:
  push zcat_path
  mov ecx, esp
  xor edx, edx
  int 0x80

  ; ============================================================================
exit_error:
; test ebx, ebx
; jnz exit_now

  ; Print copyright notice, version and internal name
  push zcat_path - copy_vers    ; bytes to write
  pop edx
  push  4                       ; SYS_write
  pop eax
  push  2                       ; stderr
  pop ebx
  mov ecx, copy_vers
  int 0x80

; exit_now:
; xor ebx, ebx
; inc ebx                       ; Exit code 1
  push 1
  pop eax
  int 0x80

; ==============================================================================
; COMPACT DATA SECTION (Appended to code)
; ==============================================================================
copy_vers:  db "(c) github/robang74 v0.80 "                      ; 26
; filename can be changed by sed up to 8 chars + ending \0
; zcat -f is cat when input isn't gzip, options up to -6c\0
; /bin/zcat can be changed by sed up to 41 chars + ending \0
; - for example: /usr/local/bin/xzcat is 20 chars + ending \0
; in do_script mode the 2 paths shrink to 20 chars + ending \0
; eof_strng helps to find the EOF, and where \0 padding starts
filename:   db "uzpexec",    0, 0                                ;  9
zcat_path:  db "/bin/zcat",       0,0,0, 0,0,0,0, 0,0,0,0, 0     ; 21
do_script:  db 0,"bin/sh",   0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0     ; 21
force_arg:  db "-f", 0,0,0,0                                     ;  6
dash_arg:   db "-", 0,                                           ;  7
eof_test:   db "U238", 0  ; useful for "make tests", only          --------
                                                                 ; 97 (tot)
; ==============================================================================
; PADDING: Aligned exactly to 512 bytes (as per skip request)
; ==============================================================================
file_end:                       ; Physical end of the binary file!
times (512 - ($ - $$)) db 0     ; Padding to 512 bytes for skip=1

; ==============================================================================
; BSS SECTION (RAM only, aligned to 512 bytes)
; ==============================================================================
bss_start equ $$ + 512

memfd:    equ bss_start + 0     ; Only variable needed besides the buffer
buf:      equ memfd + 4
bss_end:  equ buf + 512         ; Reserve 512 bytes for the buffer

