; ==============================================================================
;
; (C) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT+1 license
;
;     MIT+1: due to the extreme nature of this software, an extra clause is
;            added to the standard MIT license, which forbids everyone to
;            remove or change the authorship string also from the binary.
;            The clause rationale is rooted in security fingerprinting and
;            due to the strong -- nearly 1:1 -- match between the Assembler
;            source code and the x86 32-bit executable code (human-machine).
;
;     The MIT+1 licensing terms apply to all the previous, current and future
;     versions, unless the author provides a public legal charter allowing a
;     designated entity to be exempted from this extra clause. Comply or delete.
;
;     Note : coded with the help of Kimi and Gemini for the size reduction,
;            this aspect deepens the link between the human and the machine.
;
;    In this specific case, MIT+1 is not a derivative of the MIT license but
;    due to the peculiar and extreme nature of this source code, the license
;    acts as a direct extension to the binary code generated by it (1sc:1bc).
;
; ==============================================================================
;
; USAGE:
; - a) { cat uzpexec; rle-compress $elfbin; } > $self-extracting-executable.uzp
; - b) cat uzpexec | uzpexec [args] when uzpexec carries a compressed payload via stdin
;
; ==============================================================================
;
; Single-Process RLE Architecture:
; - 1. Reads itself (from argv[0] or stdin)
; - 2. Discards the first 512 bytes if opening itself via file path
; - 3. Creates an anonymous memfd
; - 4. Decodes the compressed RLE payload directly into the memfd using a stream buffer
; - 5. Replaces process image via execveat from the memfd
;
; Marker-Based RLE Spec:
; - Literal byte: written directly.
; - Marker byte (0xAA): followed by 1 byte of count, and 1 byte of value.
;
; ==============================================================================

BITS 32
org 0x08048000

; ==============================================================================
; ELF32 HEADER (Micro-Loader a 32-bit, Teeny ELF)
; ==============================================================================
elf_header:
  db 0x7F, 'ELF', 1, 1, 1, 0  ; e_ident (Magic, Class 32bit, Data LSB, Version)
  times 8 db 0                ; Padding for e_ident
  dw 2                        ; e_type (Executable)
  dw 3                        ; e_machine (Intel 80386)
  dd 1                        ; e_version
  dd main_start               ; e_entry (The starting point of our code)
  dd phdr - elf_header        ; e_phoff (Offset of the Program Header Table)
  dd 0                        ; e_shoff (No Section Header Table, saving bytes)
  dd 0                        ; e_flags
  dw 52                       ; e_ehsize (Size of this header)
  dw 32                       ; e_phentsize (Size of a Program Header entry)
  dw 1                        ; e_phnum (Only one segment needed)
  dw 0, 0, 0                  ; Section info (zeroed out)

phdr:
  dd 1                        ; p_type (PT_LOAD - Segment to load)
  dd 0                        ; p_offset
  dd 0x08048000               ; p_vaddr (Virtual address in memory)
  dd 0x08048000               ; p_paddr
  dd file_end - elf_header    ; p_filesz (Size of the code within the file)
  dd bss_end - elf_header     ; p_memsz (Size of the code within memory)
  dd 7                        ; p_flags (R+W+X - Read, Write, and Execute)
  dd 0x1000                   ; p_align (Standard page alignment)

; ==============================================================================
; upexec CODE (Execution starts here)
; ==============================================================================
main_start:
  ; Stack: [argc] [argv[0]] ... [argv[N]] [NULL] [envp...]
  pop eax                     ; argc (was [esp])
  mov esi, esp                ; ESI = argv
  mov [argv_ptr], esi         ; Persist original argv base pointer to BSS
  lea ebp, [esi+eax*4+4]      ; EBP = envp (callee-saved!)

  ; 1. Checking argv[0] to open input (itself or stdin)
  mov ebx, [esi]
  test ebx, ebx
  jz .stdin
  cmp byte [ebx], 0
  jz .stdin

  ; Seek for the basename of argv[0]
  mov edx, ebx                  ; edx is set at the argv[0] start
.find_end:
  inc edx
  cmp byte [edx], 0
  jnz .find_end

  ; Seeking back for the last '/' or argv[0] start
.backtrack:
  cmp edx, ebx                  ; Do we reach the argv[0]'s begin?
  je .do_strcmp                 ; - Y: do the confrontation from here
  dec edx                       ; - N: continue
  cmp byte [edx], '/'           ; Do we reach a '/' slash path-div?
  jne .backtrack                ; - N: loop again
  inc edx                       ; - Y: set EDX to basename 1st char

  ; Let's start the byte-by-byte comparison with filename var
.do_strcmp:
  mov ecx, filename

.strcmp_loop:
  mov al, [edx]
  mov ah, [ecx]
  cmp al, ah
  jne .not_uzpexec              ; If basename != filename, open the file
  test al, al                   ; Are we seeing the ending '\0'?
  jz .stdin                     ; - Y: perfect match
  inc edx
  inc ecx
  jmp .strcmp_loop              ; - N: loop again

.not_uzpexec:
  ; 2. Try to open itself (embedded payload mode, only)
  xor ecx, ecx                  ; O_RDONLY
  push 5                        ; SYS_open
  pop eax
  int 0x80
  mov edi, eax                  ; EDI = input fd (opened file)

  ; 3. Skip the fixed 512-bytes initial block (!stdin, only self-read)
  mov ecx, buf
  mov edx, 512
.skip_loop:
  push 3                        ; SYS_read
  pop eax
  mov ebx, edi                  ; input fd
  int 0x80
  test eax, eax
  jle exit_error                ; Premature EOF or read error
  sub edx, eax
  jnz .skip_loop
  jmp .memfd

.stdin:
  xor edi, edi                  ; EDI = stdin (0)

.memfd:
  mov ebx, filename             ; fd owner's name
  mov eax, 356                  ; SYS_memfd_create
  push 1                        ; MFD_CLOEXEC
  pop ecx
  xor edx, edx                  ; flags = 0
  int 0x80
  mov [memfd], eax

; ==============================================================================
; STREAM DECOMPRESSOR CORE ENGINE
; ==============================================================================
decompress_stream:
  xor ecx, ecx                  ; Force fetch_byte to trigger initial disk read
.loop:
  call fetch_byte
  jc .execute                   ; Carry flag Set -> EOF reached, branch to exec

  cmp al, 0xAA                  ; Check for our chosen RLE Magic Marker
  jne .literal                  ; Not a marker? Process as standard literal byte

  ; Handle Marker sequence: [0xAA] [Count] [Byte]
  call fetch_byte
  jc exit_error                 ; Malformed payload: trailing marker at EOF
  mov dl, al                    ; DL = Loop counter (Repetition run length)

  call fetch_byte
  jc exit_error                 ; Malformed payload: structural truncation

.rle_write:
  call write_byte
  dec dl
  jnz .rle_write
  jmp .loop

.literal:
  call write_byte
  jmp .loop

; ==============================================================================
; EXECUTION STAGE
; ==============================================================================
.execute:
  ; Closes the initial input file descriptor if it wasn't stdin
  test edi, edi
  jz .run
  push 6                        ; SYS_close
  pop eax
  mov ebx, edi
  int 0x80

.run:
  mov eax, 358                  ; SYS_execveat
  mov ebx, [memfd]              ; EBX = target memfd containing the un-rle binary
  push 0                        ; push empty string "" to the stack
  mov ecx, esp                  ; ECX = points to ""
  mov edx, [argv_ptr]           ; EDX = restored original argv array pointer
  mov esi, ebp                  ; ESI = envp (extracted from EBP)
  mov edi, 0x1000               ; EDI = AT_EMPTY_PATH flag
  int 0x80                      ; Replace process image
  jmp exit_error                ; Trap unexpected kernel errors securely

; ==============================================================================
; SUBROUTINES
; ==============================================================================

; fetch_byte: Manages stream chunk input. Returns next byte in AL.
; Sets Carry Flag (CF) on EOF or Error condition to drive loop termination.
fetch_byte:
  test ecx, ecx
  jnz .from_buf

  ; Refill the staging buffer block from the active descriptor
  push edx
  push ebx
  mov eax, 3                    ; SYS_read
  mov ebx, edi                  ; Input source descriptor
  mov ecx, buf                  ; Destination target inside memory
  mov edx, 512                  ; Block parsing ceiling size
  int 0x80
  pop ebx
  pop edx

  test eax, eax
  jle .eof                      ; branch if <= 0 (Handles EOF or physical error)

  mov ecx, eax                  ; ECX = bytes remaining in block
  mov esi, buf                  ; Reset buffer pointer to start

.from_buf:
  lodsb                         ; AL = [ESI], increments ESI
  dec ecx
  clc                           ; Clear carry (Valid byte status ready)
  ret

.eof:
  stc                           ; Set carry (Signal transmission end condition)
  ret

; write_byte: Emits a single character stored in AL to the target memfd
write_byte:
  push ecx
  push edx
  push ebx
  push eax                      ; Push char onto stack to get its address
  
  mov ecx, esp                  ; Point ECX to the byte on the stack
  mov edx, 1                    ; 1 byte length
  mov ebx, [memfd]              ; target descriptor
  mov eax, 4                    ; SYS_write
  int 0x80
  
  pop eax                       ; Clear byte structure from stack frame
  pop ebx
  pop edx
  pop ecx
  ret

; ==============================================================================
; FAULT TERMINATION
; ==============================================================================
exit_error:
  push 1                        ; SYS_exit
  pop eax
  xor ebx, ebx
  inc ebx                       ; Return code 1
  int 0x80

; ==============================================================================
; COMPACT DATA SECTION (Appended to code)
; ==============================================================================
copy_vers:  db "(c) github/robang74 v0.80 RLE", 0
filename:   db "uzpexec", 0
eof_strng:  db "elf_eof", 0

; ==============================================================================
; PADDING: Aligned exactly to 512 bytes (as per skip request)
; ==============================================================================
file_end:                       ; Physical end of the loader file binary!
times (511 - ($ - $$)) db 0     ; Padding to 512 bytes for skip=1
end_code: db 0

; ==============================================================================
; BSS SECTION (RAM only, initialized to zero by kernel)
; ==============================================================================
bss_start equ $$ + 512

memfd:    equ bss_start + 0     
argv_ptr: equ bss_start + 4     ; Holds the pointer to original argv array
buf:      equ bss_start + 8     ; Streaming input staging area 
bss_end:  equ buf + 512         ; Reserve space for buffer operations
